[phases.setup]
packages = ["libjpeg", "zlib", "gcc", "python3", "python3-dev", "make", "libjpeg-turbo", "libpng"]

[phases.build]
commands = ["pip install -r requirements.txt"]

[phases.start]
commands = ["python -m gunicorn News.wsgi:application --bind 0.0.0.0:8000"]
