[phases.setup]
packages = ["libjpeg", "zlib", "gcc", "python3", "python3-dev", "make"]

[phases.build]
commands = ["pip install -r requirements.txt"]

[phases.start]
commands = ["python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
