[phases.setup]
packages = ["libjpeg", "zlib", "gcc", "python3", "python3-dev", "make", "libjpeg-turbo", "libpng"]

[phases.build]
commands = [
  "python -m pip install -r requirements.txt",
  "python -m pip install Pillow",
  "python manage.py migrate"
]

[phases.start]
commands = [
  "python -m gunicorn News.wsgi:application --bind 0.0.0.0:8000"
]
