[phases.setup]
packages = ["libjpeg", "zlib", "gcc", "python3", "python3-dev", "make", "libjpeg-turbo", "libpng"]

[phases.build]
commands = ["pip install -r requirements.txt", "pip install Pillow"]

[phases.start]
commands = ["python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
