# Generated by Django 5.1.5 on 2025-03-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0011_article_department_alter_article_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='departments',
            field=models.CharField(choices=[('general', 'General'), ('cse', 'CSE'), ('aiml', 'AIML'), ('cs-ds', 'CS-DS')], default='general', max_length=50),
        ),
    ]
